sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack
  - $HOME/Carp

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- git clone https://github.com/carp-lang/Carp $HOME/Carp

install:
- echo "install"
- stack
- ls $HOME/Carp

script:
- echo "script"