sudo: false
language: generic

cache:
  directories:
  - $HOME/.stack
  - $HOME/Carp

addons:
  apt:
    packages:
      - libgmp-dev

matrix:
  include:
    - os: linux
    - os: osx

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- git clone https://github.com/carp-lang/Carp $HOME/Carp || true
- cd $HOME/Carp
- stack build
- stack install
- cd -
- export CARP_DIR=$HOME/Carp

install:
- echo "install"
- stack
- pwd

script:
- carp -x infornography.carp